import React, { useContext, useState } from 'react';
import { AppContext } from '../context/AppContext';
import { Pencil, Trash2 } from 'lucide-react';
export default function Archive() {
  const { diaries, updateDiary, deleteDiary } = useContext(AppContext);
  const [editingId, setEditingId] = useState(null); const [editContent, setEditContent] = useState('');
  const handleEditClick = (diary) => { setEditingId(diary.id); setEditContent(diary.content); };
  const handleUpdate = (id) => { updateDiary(id, editContent); setEditingId(null); };
  return (<div className="flex flex-col h-screen overflow-y-auto hide-scrollbar pb-32"><header className="px-6 pt-16 pb-6"><h1 className="text-[28px] font-bold text-white tracking-tight mb-2">아카이브</h1><p className="text-[#8E8E93] text-sm">지금까지 쌓인 나의 마음 기록들 ({diaries.length}개)</p></header><div className="px-5 space-y-4">{diaries.length === 0 ? (<div className="bg-[#1C1C1E] rounded-[24px] p-8 text-center text-[#8E8E93]">아직 작성된 일기가 없습니다.</div>) : (diaries.map(diary => (<div key={diary.id} className="bg-[#1C1C1E] rounded-[24px] overflow-hidden border border-white/5"><div className="flex justify-between items-center p-5 bg-white/5 border-b border-white/5"><div className="flex items-center gap-3"><span className="w-3 h-3 rounded-full shadow-[0_0_10px_currentColor]" style={{ color: diary.emotion.color, backgroundColor: diary.emotion.color }}></span><span className="text-white font-bold text-[15px]">{diary.date}</span></div><div className="flex gap-4"><button onClick={() => handleEditClick(diary)} className="text-[#8E8E93] hover:text-white transition"><Pencil className="w-4 h-4" /></button><button onClick={() => deleteDiary(diary.id)} className="text-[#8E8E93] hover:text-red-500 transition"><Trash2 className="w-4 h-4" /></button></div></div><div className="p-5 space-y-4">{editingId === diary.id ? (<div className="space-y-3"><textarea value={editContent} onChange={(e) => setEditContent(e.target.value)} className="w-full bg-black/50 text-white p-3 rounded-xl outline-none border border-white/10 min-h-[100px]" /><div className="flex gap-2 justify-end"><button onClick={() => setEditingId(null)} className="px-4 py-2 text-xs bg-[#2C2C2E] rounded-lg text-white">취소</button><button onClick={() => handleUpdate(diary.id)} className="px-4 py-2 text-xs bg-brandBlue rounded-lg text-white">저장</button></div></div>) : (<p className="text-[#D1D1D6] text-[15px] leading-relaxed whitespace-pre-wrap">{diary.content}</p>)}<div className="bg-black/30 p-4 rounded-xl space-y-3 border border-white/5 mt-4"><div><span className="text-[11px] font-bold text-[#A78BFA] px-2 py-0.5 bg-[#A78BFA]/10 rounded-full inline-block mb-1">AI 성찰 질문</span><p className="text-white text-[13px] font-medium leading-relaxed">{diary.aiQuestion}</p></div><div className="border-t border-white/5 pt-3"><span className="text-[11px] font-bold text-[#8E8E93] px-2 py-0.5 bg-white/5 rounded-full inline-block mb-1">나의 답변</span><p className="text-[#D1D1D6] text-[13px] leading-relaxed whitespace-pre-wrap">{diary.userAnswer}</p></div></div></div></div>)))}</div></div>);
}